### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by yuan-kai-design** [zhuqinfeng1999/Samba#2]
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

Traceback (most recent call last):
  File "/home/ps/train/YK-project/mamba/YK_work/Samba/./train.py", line 104, in <module>
    main()
  File "/home/ps/train/YK-project/mamba/YK_work/Samba/./train.py", line 93, in main
    runner = Runner.from_cfg(cfg)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/ps/train/YK-project/mamba/mmsegmentation-main/mmseg/models/segmentors/encoder_decoder.py", line 89, in __init__
    self.backbone = MODELS.build(backbone)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: 'module' object is not callable
Traceback (most recent call last):
  File "/home/ps/train/YK-project/mamba/YK_work/Samba/./train.py", line 104, in <module>
    main()
  File "/home/ps/train/YK-project/mamba/YK_work/Samba/./train.py", line 93, in main
    runner = Runner.from_cfg(cfg)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/ps/train/YK-project/mamba/mmsegmentation-main/mmseg/models/segmentors/encoder_decoder.py", line 89, in __init__
    self.backbone = MODELS.build(backbone)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: 'module' object is not callable
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2025358) of binary: /home/ps/anaconda3/envs/doctor/bin/python
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ps/anaconda3/envs/doctor/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

./train.py FAILED

Failures:
[1]:
  time      : 2024-04-10_21:30:57
  host      : ps-MS-7E07
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2025359)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Root Cause (first observed failure):
[0]:
  time      : 2024-04-10_21:30:57
  host      : ps-MS-7E07
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2025358)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

run:
bash dist_train.sh /home/ps/train/YK-project/mamba/YK_work/Samba/configs/samba_upernet-15k_loveda-512x512_6e4.py 2 --work-dir /home/ps/train/YK-project/mamba/YK_work/work_dir --amp
How can I solve it?

**Comment by zhuqinfeng1999** [comment]
Thanks for your interest in our work.
This error may have occurred because you were not able to successfully configure the mmseg environment. I suggest using the same environment as us to run (Ubuntu 20.04, CUDA 12.4, pytorch 2.0.1, python 3.10). 
Of course, you could also try using the configuration file included with the mmseg library for training in loveda, such as: "deeplabv3plus_r18-d8_4xb4-80k_loveda-512x512.py", to determine whether the issue is with the mmseg environment setup. If the issue is related to the mmseg configuration, I recommend checking [mmseg](https://github.com/open-mmlab/mmsegmentation) to see if anyone has encountered the same problem.
If you have any more questions, you are welcome to discuss with me.
